
CREATE VIEW 부서별최고급여 AS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE (SALARY, DEPARTMENT_ID) IN (SELECT MAX(SALARY), DEPARTMENT_ID
                                  FROM EMPLOYEES
                                  GROUP BY DEPARTMENT_ID);

SELECT * FROM 부서별최고급여;                                  
-- VIEW : 가상의 테이블
-- 복잡한 SELECT 문을 저장하기 위해 사용한다
SELECT EMPLOYEE_ID, SALARY, ms.DEPARTMENT_ID, CITY
FROM LOCATIONS l, 부서별최고급여 ms, DEPARTMENTS d
WHERE ms.DEPARTMENT_ID=d.DEPARTMENT_ID AND d.LOCATION_ID=l.LOCATION_ID;

-- 각부서별 부서번호, 부서명, 도시명, 나라이름을 가지는 VIEW(DEPARTVIEW)를 만들어주세요
-- 각 도시별 몇명이 근무하는지 출력해주세요
CREATE VIEW DEPARTVIEW AS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, CITY, COUNTRY_NAME
FROM DEPARTMENTS d, LOCATIONS l, COUNTRIES c
WHERE d.LOCATION_ID=l.LOCATION_ID AND l.COUNTRY_ID=c.COUNTRY_ID;

SELECT COUNT(e.EMPLOYEE_ID) AS "인원수", di.CITY
FROM DEPARTVIEW di, EMPLOYEES e
WHERE di.DEPARTMENT_ID=e.DEPARTMENT_ID
GROUP BY CITY; 


-- 시퀀스 : 연속된 숫자를 생성하는 객체
CREATE SEQUENCE 블로그시퀀스
INCREMENT BY 1
START WITH 1;

ALTER TABLE 네이버블로그 DROP CONSTRAINT 블로그_회원ID_FK;

SELECT * FROM 네이버블로그;
INSERT INTO 네이버블로그 VALUES (블로그시퀀스.NEXTVAL, '맛집', '짜장면', 'TEST');

-- TOP-N : 상위 N 개만 출력하자!
-- ROWNUM : SELECT문을 통해 출력되는 행의 갯수를 제한
SELECT * 
FROM 네이버블로그
WHERE ROWNUM<=3;

-- 전직원중 제일 급여를 많이 받는 직원 상위 5명만 출력해주세요!
CREATE VIEW BESTSAL AS
SELECT SALARY, FIRST_NAME 
FROM EMPLOYEES
ORDER BY SALARY DESC NULLS LAST;

SELECT *
FROM BESTSAL
WHERE ROWNUM<=5;

SELECT FIRST_NAME , SALARY
FROM (SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC NULLS LAST)
WHERE ROWNUM <= 5;
